# Generated by Django 4.1 on 2022-09-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='date_task',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='description_task',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='title_task',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='user_todo',
            new_name='user',
        ),
    ]
